// Generated by gencpp from file lidar/lidar.msg
// DO NOT EDIT!


#ifndef LIDAR_MESSAGE_LIDAR_H
#define LIDAR_MESSAGE_LIDAR_H

#include <ros/service_traits.h>


#include <lidar/lidarRequest.h>
#include <lidar/lidarResponse.h>


namespace lidar
{

struct lidar
{

typedef lidarRequest Request;
typedef lidarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lidar
} // namespace lidar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lidar::lidar > {
  static const char* value()
  {
    return "876c4429855d6020f9989528c5e136d4";
  }

  static const char* value(const ::lidar::lidar&) { return value(); }
};

template<>
struct DataType< ::lidar::lidar > {
  static const char* value()
  {
    return "lidar/lidar";
  }

  static const char* value(const ::lidar::lidar&) { return value(); }
};


// service_traits::MD5Sum< ::lidar::lidarRequest> should match
// service_traits::MD5Sum< ::lidar::lidar >
template<>
struct MD5Sum< ::lidar::lidarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lidar::lidar >::value();
  }
  static const char* value(const ::lidar::lidarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar::lidarRequest> should match
// service_traits::DataType< ::lidar::lidar >
template<>
struct DataType< ::lidar::lidarRequest>
{
  static const char* value()
  {
    return DataType< ::lidar::lidar >::value();
  }
  static const char* value(const ::lidar::lidarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lidar::lidarResponse> should match
// service_traits::MD5Sum< ::lidar::lidar >
template<>
struct MD5Sum< ::lidar::lidarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lidar::lidar >::value();
  }
  static const char* value(const ::lidar::lidarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lidar::lidarResponse> should match
// service_traits::DataType< ::lidar::lidar >
template<>
struct DataType< ::lidar::lidarResponse>
{
  static const char* value()
  {
    return DataType< ::lidar::lidar >::value();
  }
  static const char* value(const ::lidar::lidarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIDAR_MESSAGE_LIDAR_H
